cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'node'
brew 'nvm'
brew 'ack'
brew 'awscli'
brew 'graphviz'

#cask 'google-chrome'
#cask 'firefox'
#cask 'iterm2'
cask 'sublime-text'
cask 'docker'
cask 'adobe-acrobat-reader'
#cask 'charles'
#cask 'spotify'
#cask 'slack'
cask 'vlc'
#cask 'skype'
#cask 'visual-studio-code'
#cask 'telegram'
